[package]
name = "yurilang"
description = "An esoteric language with a spinkle of Yuriness :3"
authors = ["Kazooki123 <mgamerdinge146@gmail.com>"]
keywords = ["language", "runtime", "compiler"]
repository = "https://github.com/Kaziiki123/yurilang"
version = "1.7.0"
edition = "2024"
readme = "README.md"
license = "GPL-3.0-only"

[workspace]
members = ["pkm/yuu"]

[lib]
name = "yurilang"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module", "abi3-py38"]}
