#!/usr/bin/env python3
"""
YuriLang Installer
"She found her way in. Now so can you." 🦢

Usage:
    python install.py          # auto-detect OS
    python install.py --user   # install to user dir (no sudo)
    python install.py --uninstall
"""

import sys
import os
import platform
import shutil
import subprocess
import argparse
from pathlib import Path


PINK = "\033[38;5;218m"
PURPLE = "\033[38;5;183m"
GREEN = "\033[38;5;156m"
RED = "\033[38;5;203m"
YELLOW = "\033[38;5;228m"
RESET = "\033[0m"
BOLD = "\033[1m"


def p(msg, color=RESET):
    print(f"{color}{msg}{RESET}")


def banner():
    print(f"""
{PINK}{BOLD}
  ╔══════════════════════════════════════╗
  ║         Y U R I L A N G              ║
  ║   "Yuring Complete since 2026"       ║
  ║              🪷                      ║
  ╚══════════════════════════════════════╝
{RESET}""")


def check_python():
    p("Checking Python version...", PURPLE)
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 13):
        p(f"| 💔 Python 3.13 required. You have {version.major}.{version.minor}", RED)
        p("|> 💡 Hint: https://python.org/downloads", YELLOW)
        sys.exit(1)
    p(f"  ✅ Python {version.major}.{version.minor}.{version.micro}", GREEN)


def check_dependencies():
    p("Checking dependencies...", PURPLE)
    deps = ["reportlab", "raylib"]
    missing = []
    for dep in deps:
        try:
            __import__(dep)
            p(f"  ✅ {dep}", GREEN)
        except ImportError:
            missing.append(dep)
            p(f"  ⚠️  {dep} not found", YELLOW)

    if missing:
        p("\n  Installing missing dependencies...", PURPLE)
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
        p("  Dependencies installed", GREEN)


def check_nasm():
    p("Checking NASM (optional — needed for @kumitate)...", PURPLE)
    if shutil.which("nasm"):
        p("  NASM found!", GREEN)
    else:
        p("  ⚠️  NASM not found — @kumitate inline assembly won't work", YELLOW)
        p("  Hint: sudo apt install nasm  /  pkg install nasm (Termux)", YELLOW)


def get_yurilang_root():
    return Path(__file__).parent.resolve()


UNIX_SCRIPT = """\
#!/bin/sh
# YuriLang launcher — "yuri" command
# Auto-generated by install.py
exec python3 "{root}/yuri.py" "$@"
"""


def install_unix(user_install=False):
    root = get_yurilang_root()

    if user_install:
        bin_dir = Path.home() / ".local" / "bin"
        bin_dir.mkdir(parents=True, exist_ok=True)
    else:
        bin_dir = Path("/usr/local/bin")

    script_path = bin_dir / "yuri"

    p(f"\nInstalling to {script_path}...", PURPLE)

    try:
        script_content = UNIX_SCRIPT.format(root=root)
        script_path.write_text(script_content)
        script_path.chmod(0o755)
        p(f"  🟢 Installed: {script_path}", GREEN)
    except PermissionError:
        p(f"  💔 Permission denied writing to {bin_dir}", RED)
        p("   💡 Hint: Try --user flag or run with sudo", YELLOW)
        sys.exit(1)

    # verify it's on PATH
    if str(bin_dir) not in os.environ.get("PATH", ""):
        p(f"\n  ⚠️  {bin_dir} may not be on your PATH", YELLOW)
        if user_install:
            p("  💡 Add to your shell config:", YELLOW)
            p('     export PATH="$HOME/.local/bin:$PATH"', YELLOW)

    return script_path


WIN_BATCH = """\
@echo off
:: YuriLang launcher — "yuri" command
:: Auto-generated by install.py
python "{root}\\yuri.py" %*
"""

WIN_PS1 = """\
# YuriLang launcher — "yuri" command
# Auto-generated by install.py
& python "{root}\\yuri.py" @args
"""


def install_windows(user_install=False):
    root = get_yurilang_root()

    if user_install:
        # install to user's local bin
        bin_dir = Path.home() / "AppData" / "Local" / "Programs" / "YuriLang"
    else:
        # install to System32 (admin perms needed)
        bin_dir = Path(os.environ.get("SystemRoot", "C:\\Windows")) / "System32"

    bin_dir.mkdir(parents=True, exist_ok=True)

    bat_path = bin_dir / "yuri.bat"
    ps1_path = bin_dir / "yuri.ps1"

    p(f"\nInstalling to {bin_dir}...", PURPLE)

    try:
        bat_path.write_text(WIN_BATCH.format(root=root))
        ps1_path.write_text(WIN_PS1.format(root=root))
        p(" |  yuri.bat installed", GREEN)
        p(" |  yuri.ps1 installed", GREEN)
    except PermissionError:
        p(" | Permission denied. Run as Administrator or use --user", RED)
        sys.exit(1)

    # add to PATH if user install
    if user_install:
        _add_to_windows_path(str(bin_dir))

    return bat_path


def _add_to_windows_path(new_dir):
    """Add directory to Windows user PATH via registry."""
    try:
        import winreg

        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_ALL_ACCESS
        )
        current_path, _ = winreg.QueryValueEx(key, "Path")

        if new_dir not in current_path:
            new_path = current_path + ";" + new_dir
            winreg.SetValueEx(key, "Path", 0, winreg.REG_EXPAND_SZ, new_path)
            p(f" | Added to PATH: {new_dir}", GREEN)
            p("  | Restart your terminal for PATH changes to take effect", YELLOW)
        else:
            p("  | Already in PATH", GREEN)

        winreg.CloseKey(key)
    except Exception as e:
        p(f" | Could not update PATH automatically: {e}", YELLOW)
        p(f" | Add manually: {new_dir}", YELLOW)


def install_termux():
    """Special case for Termux on Android."""
    root = get_yurilang_root()
    bin_dir = Path(os.environ.get("PREFIX", "/data/data/com.termux/files/usr")) / "bin"
    script_path = bin_dir / "yuri"

    p(f"\nDetected Termux — installing to {script_path}...", PURPLE)

    script_content = UNIX_SCRIPT.format(root=root)
    try:
        script_path.write_text(script_content)
        script_path.chmod(0o755)
        p(f"  ✅ Installed: {script_path}", GREEN)
    except PermissionError:
        p("  💔 Permission denied", RED)
        sys.exit(1)

    return script_path


def uninstall():
    p("\nUninstalling YuriLang...", PURPLE)

    candidates = [
        Path("/usr/local/bin/yuri"),
        Path.home() / ".local" / "bin" / "yuri",
        Path(os.environ.get("PREFIX", "")) / "bin" / "yuri",  # Termux
    ]

    if platform.system() == "Windows":
        candidates += [
            Path.home() / "AppData" / "Local" / "Programs" / "YuriLang" / "yuri.bat",
            Path.home() / "AppData" / "Local" / "Programs" / "YuriLang" / "yuri.ps1",
            Path(os.environ.get("SystemRoot", "C:\\Windows")) / "System32" / "yuri.bat",
            Path(os.environ.get("SystemRoot", "C:\\Windows")) / "System32" / "yuri.ps1",
        ]

    removed = False
    for path in candidates:
        if path.exists():
            path.unlink()
            p(f"  ✅ Removed: {path}", GREEN)
            removed = True

    if not removed:
        p("  ⚠️  No YuriLang installation found", YELLOW)
    else:
        p("\n  💔 YuriLang has been uninstalled.", PINK)
        p("  She'll always be in your heart though. 🪷", PINK)


def success_message(install_path):
    p(f"""
{GREEN}{BOLD}  ✅ YuriLang installed successfully!{RESET}

{PURPLE}  Get started:{RESET}

  {PINK}yuri program.yuri{RESET}              {PURPLE}# interpret{RESET}
  {PINK}yuri program.yuri --bytecode{RESET}   {PURPLE}# compile to .yuric{RESET}
  {PINK}yuri program.yuric --vm{RESET}        {PURPLE}# run bytecode{RESET}
  {PINK}yuri program.yuri --compile{RESET}    {PURPLE}# compile to ASM{RESET}
  {PINK}yuri program.yuri --wasm{RESET}       {PURPLE}# compile to WASM{RESET}
  {PINK}yuri{RESET}                           {PURPLE}# launch REPL{RESET}

{PURPLE}  Write your first program:{RESET}

  {PINK}@wlw:{RESET}
  {PINK}    @confess "Hello, World!"{RESET}

{PURPLE}  Documentation:{RESET}
  {YELLOW}  https://codeberg.org/Kazooki123/yurilang{RESET}

{PINK}  "Yuring Complete since 2025"{RESET}
""")


def main():
    parser = argparse.ArgumentParser(description="YuriLang Installer")
    parser.add_argument(
        "--user",
        action="store_true",
        help="Install to user directory (no sudo/admin required)",
    )
    parser.add_argument("--uninstall", action="store_true", help="Uninstall YuriLang")
    args = parser.parse_args()

    banner()

    if args.uninstall:
        uninstall()
        return

    # detect OS
    system = platform.system()
    is_termux = "com.termux" in os.environ.get(
        "PREFIX", ""
    ) or "com.termux" in os.environ.get("HOME", "")

    check_python()
    check_dependencies()
    check_nasm()

    p(f"\nDetected OS: {system}", PURPLE)
    if is_termux:
        p("  📱 Termux detected!", PINK)

    # install
    if is_termux:
        path = install_termux()
    elif system == "Windows":
        path = install_windows(user_install=args.user)
    else:
        path = install_unix(user_install=args.user)

    success_message(path)


if __name__ == "__main__":
    main()
