[project]
name = "yurilang"
version = "1.7.0"
description = "A Yuri-themed esoteric programming language 🧡"
authors = [
    { name="starloexoliz11" }
]
readme = "README.md"
requires-python = ">=3.13"

[project.scripts]
yuri = "yurilang.yuri:main"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "yurilang"
