name: Run & Test YuriLang

on:
  push:
  workflow_dispatch:

jobs:
  run-yurilang:
    runs-on: docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install SYS Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
              libasound2-dev \
              mesa-common-dev \
              libx11-dev \
              libxrandr-dev \
              libxi-dev \
              libgl1-mesa-dev \
              libglu1-mesa-dev \
              pkg-config \
              libsdl2-dev \
              libfreetype6-dev \
              libportmidi-dev \
              python3-dev
     
      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install llvmlite raylib pygame-ce

      - name: Run and Test YuriLang
        run: |
          python yuri.py example/test.yuri
