name: Release Builds

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux
            artifact_name: linux
          - os: macos-latest
            target: darwin
            artifact_name: darwin
          - os: windows-latest
            target: windows
            artifact_name: windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip for ${{ matrix.target }}
        run: |
          chmod +x bin/* || true
          cd bin || exit 1
          zip -r ../\( {{ github.event.release.tag_name }}- \){{ matrix.artifact_name }}.zip .
        shell: bash

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./\( {{ github.event.release.tag_name }}- \){{ matrix.artifact_name }}.zip
          asset_name: \( {{ github.event.release.tag_name }}- \){{ matrix.artifact_name }}.zip
          asset_content_type: application/zip