name: Test Yurilang's LLVM

on:
  push:
  workflow_dispatch:

jobs:
  run-yurilang:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install LLVM, Clang, and GCC
        run: |
          sudo apt update
          sudo apt install -y llvm clang gcc

      - name: Verify LLVM tools
        run: |
          llc --version
          clang --version
          gcc --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install llvmlite
        run: |
          pip install llvmlite

      - name: Run a Yuri file with the LLVM flag
        run: |
          python main.py example/helloworld.yuri --llvm


      - name: Compile using llc + gcc
        run: |
          llc -relocation-model=pic example/helloworld.ll -o example/helloworld.s
          gcc example/helloworld.s -o program
          ./program

      - name: Compile directly using clang
        run: |
          clang example/helloworld.ll -o program_clang
          ./program_clang